### ISSUE TITLE
Using an environment value for appdata roaming on Windows instead of FOLDERID_RoamingAppData.

### ISSUE THREAD

**Issue by Flaminator** [ziglibs/known-folders#13]
Is there any reason that on the following line: [known-folders.zig#L249](https://github.com/ziglibs/known-folders/blob/f0f418887b1a0cd79fa2651abce31f7e1cdedfc9/known-folders.zig#L249) an environment variable is used instead of a GUID?
Microsoft defines the ```FOLDERID_RoamingAppData``` constant in https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid for targeting Appdata so I would expect that to get used.

**Comment by MasterQ32** [comment]
Maybe because i couldn't find it. Not sure though… :see_no_evil:
