### ISSUE TITLE
XDG_CONFIG_DIRS interpreted incorrectly

### ISSUE THREAD

**Issue by enkore** [ziglibs/known-folders#28]
Most XDG base directory envvars just point to a single directory, but XDG_CONFIG_DIRS is a search path - currently it's expected to contain a single directory instead. The default value is also set to `/etc/`, while the XDG spec calls for `/etc/xdg`.

Given the name global_configuration I'd guess we should just use `/etc` here.

**Comment by vrischmann** [comment]
Here's what I get on Fedora 35:
```
$ echo $XDG_CONFIG_DIRS
/home/vincent/.config/kdedefaults:/etc/xdg:/usr/share/kde-settings/kde-profile/default/xdg
```

I only found out about this because it breaks zls which tries to [use this as a path](https://github.com/zigtools/zls/blob/18a23c1aa22c9746448477b77dc93c4b224181b5/src/main.zig#L1716-L1724).
