### ISSUE TITLE
`std.os.getenv` no longer usable on wasi

### ISSUE THREAD

**Issue by leecannon** [ziglibs/known-folders#39]
When targeting wasm32-wasi the below error is shown, this is due to https://github.com/ziglang/zig/pull/17140.

The easy fix is to replace every usage of `std.os.getenv` in `getPathXdg` with `std.process.getEnvVarOwned`, but that would pessimize non-wasi.

```
$ zig test known-folders.zig -target wasm32-wasi -freference-trace
/home/lee/zig/0.12.0-dev.378+4f952c7e0/files/lib/std/os.zig:1912:9: error: std.os.getenv is unavailable for WASI. See std.process.getEnvMap or std.process.getEnvVarOwned for a cross-platform API.
        @compileError("std.os.getenv is unavailable for WASI. See std.process.getEnvMap or std.process.getEnvVarOwned for a cross-platform API.");
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    getPathXdg: known-folders.zig:202:32
```

**Comment by squeek502** [comment]
I could be wrong, but it seems like there might be an argument that these `getenv` calls shouldn't happen when targeting WASI at all. What could `HOME` contain that would make sense in a WASI environment (which doesn't support absolute paths)? In fact, WASI being lumped into this branch:

https://github.com/ziglibs/known-folders/blob/master/known-folders.zig#L128-L131

seems a bit strange on its own.
