### ISSUE TITLE
xdg dirs on mac

### ISSUE THREAD

**Issue by nycex** [ziglibs/known-folders#6]
Some command line applications use the XDG Base Directory Specification also on mac.
Do we want to support this use case?

**Comment by MasterQ32** [comment]
That's a good question. I think it should be configurable via some `pub fn known_folder_config = .{ .enable_xdg = true };`
Shouldn't be that hard to implement those for MAC

**Comment by nycex** [comment]
Do you mean `pub const known_folder_const = ...`?
Also I'm not sure if we need a struct for this, are there any other occurances where me might need a config passed?

**Comment by MasterQ32** [comment]
Ah yes. A struct is future proof and can be expanded without having waaay to much global variables in the end

**Comment by nycex** [comment]
I agree, I think I'll implement something like that tomorrow.

**Comment by nycex** [comment]
Should we do this as a function argument or as a global variable?

**Comment by MasterQ32** [comment]
I'd use it as a root-configuration thing:

```zig
const known_folders = @import("known-folders");

pub const known_folders_config = .{
    .enable_xdg_on_mac = true,
};
```

I think an app both wants to use XDG and not XDG at the same time

**Comment by nycex** [comment]
I think you are right, but you mean `var` instead of `const`, right?

**Comment by MasterQ32** [comment]
No, this *should* be a constant, as we can then `comptime` enable/disable the code. It's similar to the pattern that `std` uses for `io_mode = .evented` and such

**Comment by nycex** [comment]
Oh wait never mind you mean in the root file of the program that is using known-folders?
I'm not sure about that, that seems a bit like magic

**Comment by MasterQ32** [comment]
Yes. It's a common idiom for Zig `std`, so i think that's okay. It's way better than an `#ifdef` anyways and it's a library configuration, not something that should be runtime-decided
